#!/usr/bin/env bash

export WLR_NO_HARDWARE_CURSORS=1
export XDG_SESSION_TYPE=wayland
export QT_QPA_PLATFORM=wayland
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export MOZ_ENABLE_WAYLAND=1

if command -v nvidia-smi > /dev/null; then
  using_nvidia=true
fi

if [ $using_nvidia = true ]; then
    # ENV-VAR fixes for Sway using NVIDIA GPUs. (i'm sorry, nvidia sucks.)
    export WLR_RENDERER=vulkan
    export MOZ_USE_XINPUT2=1
    export GBM_BACKEND=nvidia-drm
    export __GL_GSYNC_ALLOWED=0
    export __GL_VRR_ALLOWED=0
    export __GLX_VENDOR_LIBRARY_NAME=nvidia
    export XWAYLAND_NO_GLAMOR=1
fi

exec sway --unsupported-gpu